stages:          
  - build
  - syntax-test
  - semantic-test
  - backend-test

build-job:       
  stage: build
  script:
    - sbt clean compile

semantic-test-job:
  stage: semantic-test
  script:
    - sbt clean "testOnly semantic_tests.*"

syntax-test-job:
  stage: syntax-test
  script:
    - sbt clean "testOnly syntax_tests.*"

backend-test-job:
  stage: backend-test
  script:
    - sbt clean "testOnly backend_tests.*"

